### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by AnnieKJR**
format update

### CODE REVIEW

**Review by lajiaopingzi — COMMENTED** [review]
Need to judge whether there is any input in the position that has been inputted, Avoid data overwriting.

**Review by ahhuh-ly — COMMENTED** [review]
Need to add a hint for player’s input errors when the player inputs a figure outside the set board.

**Review by ahhuh-ly — COMMENTED** [review]
Need to judge whether there is any input in the position that has been inputted.

**Review by lajiaopingzi — COMMENTED** [review]
"std::cout << "Which cell to mark? i:[1..3], j:[1..3]: "; "
in this code, arrays(game) are defined as 0-2, why let user input  i:[1..3]/j:[1..3] in the code?

**Review by ahhuh-ly — COMMENTED** [review]
Need to add comments “row” in the first category of isWin function after “bool win =false;”

**Comment by AnnieKJR** [comment]
OK!

**Review by lajiaopingzi — APPROVED** [review]

**Review by ahhuh-ly — APPROVED** [review]
Approve.

**Pull request merged**
